language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# TRAVIS CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build --stacktrace"

before_deploy:
  - mkdir -p before-deploy/
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../&& mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/myspringbootproject.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myspringbootproject
    region: ap-northeast-2
    skip_cleanup: true
    acl: private #.ZIP access private
    local_dir: deploy
    wait-until-deploayed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: myspringbootproject
    key: myspringbootproject.zip
    bundle_type: zip
    application: MySpringBootProject
    deployment_group: MySpringBootProject
    region: ap-northeast-2
    wait-until-deploy: true

# Send an Email When CI build is done
notifications:
  email:
    recipients:
      - kyliethedev@gmail.com
