language: java
jdk:
  - openjdk11

branches:
  only:
    - master

# TRAVIS CI Server Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# Send an Email When CI is success
notifications:
  email:
    recipients:
      - kyliethedev@gmail.com